apiVersion: v2
name: global-chart
description: "Reusable Helm chart providing common building blocks—Deployments, Services, Ingress, Jobs, and more—for broadly adaptable Kubernetes applications."

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1

# Project URLs
home: https://github.com/filippomerante/global-chart
sources:
  - https://github.com/filippomerante/global-chart

# Chart maintainers
maintainers:
  - name: Filippo Merante Caparrotta

# Search keywords
keywords:
  - deployment
  - service
  - ingress
  - cronjob
  - hooks
  - kubernetes
  - multi-deployment

# Minimum Kubernetes version
kubeVersion: ">=1.19.0-0"
